#!/usr/bin/env bash
set -eo pipefail

main() {
  declare FILE_NAME="$1"
  mkdir -p test-results/bats
  pushd test-results/bats >/dev/null
  bats --formatter bats-format-junit -e -T -o ../../test-results/bats "$FILE_NAME.bats"
  popd >/dev/null
}

main "$@"
